### ISSUE TITLE
Release milestones (TODOs)

### ISSUE THREAD

**Issue by chessai** [nikita-volkov/refined#9]
- [x] Make sure everything has docs
- [x] Improve pretty-printing of `RefineException`s
- [X] Add more instances to Refined.Orphan
    - [x] containers
        - [x] Data.IntMap
        - [x] Data.IntMap.Lazy
        - [x] Data.Map
        - [x] Data.Map.Lazy
        - [x] Data.Sequence
        - [x] Data.Set
        - [x] Data.Tree
- [x] Add a test suite to ensure that predicates are correct
- [x] Add a README.md
